name: QA bento amr64 opal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - "os=linux"
      - "arch=arm64"
      - "engflow-cluster=opal"
      - "engflow-bento-name=qa-test-gh-arm64"
      - "engflow-bento-allow-save=true"
      - "engflow-job-type=${{github.event_name}}-${{github.ref_name}}"
      - "engflow-run-id=${{github.run_id}}"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run presubmit checks
        run: |
          bazel test //...
